version: '3.8'

services:
  localstack:
    container_name: shortlink-localstack
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "./.localstack:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
